# Generated by Django 3.1.3 on 2021-12-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
