# Generated by Django 3.1.3 on 2021-11-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='number_of_votes',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
