# Generated by Django 3.1.3 on 2021-11-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_bookmark_number_of_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='number_of_votes',
            field=models.IntegerField(default=1),
        ),
    ]
