# Generated by Django 3.1.3 on 2021-12-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20211129_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='number_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
