# Generated by Django 3.1.3 on 2021-12-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20211205_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='number_of_votes',
            field=models.IntegerField(default=1),
        ),
    ]
